# Generated by Django 3.2.1 on 2021-05-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_or_below', models.CharField(choices=[('Above', 'Above'), ('Below', 'Below')], max_length=10)),
                ('price', models.FloatField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_currency', to='currencies.currency')),
                ('on_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_on_platform', to='utils.platform')),
                ('price_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_price_in', to='currencies.currency')),
            ],
        ),
    ]
